
[[channels]]
  name   = "images"
  bands = [1, 2, 3]

[[classes]]
  title = "Background"
  color = "transparent"

[[classes]]
  title = "Building"
  color = "deeppink"

[[classes]]
  title = "Foundation"
  color = "pink"

[model]
  nn = "Albunet"
  loader = "SemSeg"
  encoder = "resnet50"

[train]
  bs = 4
  loss = "Lovasz"
  da = {name="RGB", p=1.0}
  metrics = ["IoU", "QoD"]
  optimizer = {name="Adam", lr=0.000025}


